var startingArr = [
{wordValue: 'Lannister'},
{wordValue: 'Moo'},
{wordValue: 'LearnApp'},
{wordValue: 'Makerpass'},
{wordValue: 'Zoom'},
{wordValue: 'Moo'},
{wordValue: 'Targaryen'},
{wordValue: 'Meow'},
{wordValue: 'Pep Talk'},
{wordValue: 'Party Parrot'},
{wordValue: 'Help Desk'},
{wordValue: 'Townhall'},
{wordValue: 'Codybot'},
{wordValue: 'Angular'},
{wordValue: 'React'},
{wordValue: 'Tyrell'},
{wordValue: 'Backbone'},
{wordValue: 'Node'},
{wordValue: 'Squishy-Mic'},
{wordValue: 'Greenfield'},
{wordValue: 'Legacy'},
{wordValue: 'Spectator Bot'},
{wordValue: 'Shepherd'},
{wordValue: 'Social Hack Night'},
{wordValue: 'BeesBeesBees'},
{wordValue: 'SubClass Dance Party'},
{wordValue: 'Chatterbox'},
{wordValue: 'Precourse'},
{wordValue: 'Thesis'},
{wordValue: 'Pomander'},
{wordValue: 'Shortly'},
{wordValue: 'recast.ly'},
{wordValue: 'Martell'},
{wordValue: 'Barathean'},
{wordValue: 'Stark'},
{wordValue: 'HRR Cribs'},
{wordValue: 'Tapouts'}
]

module.exports = startingArr